name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - source/**
      - .github/workflows/publish-pages.yml
      - requirements.in

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python install -r requirements.in
      - name: Build document
        run: |
          make html
          rm -r build/html/_sources
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
